# Generated by Django 4.2 on 2023-12-08 19:11

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="expiration",
            field=models.DateTimeField(default=accounts.models.default_expiration),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
